# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build bionic docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile.bionic"
          tags: ddebtest:bionic
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Build focal docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile.focal"
          tags: ddebtest:focal
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Build jammy docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile.jammy"
          tags: ddebtest:jammy
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Run bionic test
        uses: addnab/docker-run-action@v3
        if: always()
        with:
          image: ddebtest:bionic
          run: /usr/local/bin/ddeb_test.sh noping

      - name: Run focal test
        uses: addnab/docker-run-action@v3
        if: always()
        with:
          image: ddebtest:focal
          run: /usr/local/bin/ddeb_test.sh noping

      - name: Run jammy test
        uses: addnab/docker-run-action@v3
        if: always()
        with:
          image: ddebtest:jammy
          run: /usr/local/bin/ddeb_test.sh noping
